[tool.poetry]
name = "project-4"
version = "0.1.0"
description = ""
authors = ["Victor Zucchetti <victorzucchetti@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flet = "^0.22.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
